name: build-app

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository...
        uses: actions/checkout@v4
      - name: Installing java...
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "maven"
      - name: Compiling application...
        run: |
          mvn clean install
      - name: Upload artifact... 
        uses: actions/upload-artifact@v4
        with:
          name: spring-app 
          path: target/app.jar